Name = input("Enter your Name:")
branch = input("Enter the branch:")
gender = input("Your Gender:")
College = input("Enter your College name:")
age = int(input("Enter your Age:"))
print("Name:",Name)
print("Branch:",branch)
print("Gender:",gender)
print("College:",College)
print("Age:",age)
